### ISSUE TITLE
Select specific devices to disconnect 

### ISSUE THREAD

**Issue by Mat-thieu** [odlp/bluesnooze#1]
Great simple solution, thanks for providing it!

Maybe down the line this could include a list of known devices and you can select which ones will disconnect on sleep?

**Comment by odlp** [comment]
Hi @Mat-thieu,

Glad you've found Bluesnooze useful.

I like your idea but unfortunately I don't think it's possible to implement on modern versions of macOS. I had a look into a couple of the answers from this Ask Different question:
https://apple.stackexchange.com/questions/159548/prevent-auto-pairing-for-certain-devices-bluetooth

But none of the solutions seem to work any longer (I'm not an expert in Cocoa / Bluetooth APIs so there might be a solution, but I don't know what it might it be).

Thanks,
Oli
