### ISSUE TITLE
It doesn't work when the mac shuts down?

### ISSUE THREAD

**Issue by trusk89** [odlp/bluesnooze#10]
Or it doesn't work on big sur?

My usecase is I need it to work when I sleep my mac or shut it down, so my trackpad disconnects and I can move it to my other mac. Doesn't it work when the mac shuts down?

**Comment by odlp** [comment]
Hi @trusk89,

I wonder if this might be a general Bluetooth problem with your peripheral? When I shut down my Macbook Pro my headphones automatically disconnect (this is without Bluesnooze, the powering down Mac disconnects anyway).

Bluesnooze is currently focused on changing connections for _sleeping_ Macs only, it shouldn't really be required for Macs which have been shutdown. 

If you find it's not working when you put the Mac to sleep then please do feel free to leave further info.

Best regards,
Oli

**Comment by odlp** [comment]
@trusk89 not sure if this helps, but this question / answer on Ask Different implies the Apple trackpads can only be paired with one device at a time: https://apple.stackexchange.com/a/41656/89456

**Comment by trusk89** [comment]
Hey @odlp 
It's more complicated than that I'm afraid :)
Magic accessories keep the connection alive even when the Mac is turned off. For instance if my Mac is off, I can click on my Magic trackpad and it boots up.
Regarding the answer on stack exchange, it's not really correct: it can't be connected to the multiple macs at the same time, but I can force a connection to another mac if the first one is has it's bluetooth off. The idea here is that it works if I manually turn off my BT connection from my mac before I shut it down. That's why I was hoping Bluesnooze would also turn it off on shutdown also. 
But I understand if it's not a supported usecase.
Maybe I'll try a fork when I have some time and see if I can also add the shutdown support.

**Comment by odlp** [comment]
@trusk89 thanks for clarifying! I've updated the app to turn bluetooth off when the Mac is going to sleep _or_ shutdown.

You can either `brew upgrade bluesnooze` or [download v1.1](https://github.com/odlp/bluesnooze/releases/tag/v1.1). Let me know if it works for you 😃

**Comment by trusk89** [comment]
Thanks @odlp I'll give it a try!

**Comment by trusk89** [comment]
I'll close this for now, thank you!
