### ISSUE TITLE
No longer re-activates Bluetooth on wake

### ISSUE THREAD

**Issue by gingerbeardman** [odlp/bluesnooze#18]
In MacOS 12 (Monterey), this does not work as expected.

- The application does successfully disable Bluetooth
- but the application does not re-enable Bluetooth on wake

Specs
- macOS 12.6.3 (21G419)
- Apple silicon M1 Pro MBP

I believe Apple have made significant changes to IOBluetooth recently, and now support on Apple silicon and Intel vary.

**Comment by quocnm102** [comment]
in macos 13.2 ventura, macbook pro 2017 13inch non-touch chipset intel, using dongle external bluetooth usb,
after wake up macbook, macos doesn't re-enable bluetooth too. I re-enable manual but it still no affect.

**Comment by YubinXie** [comment]
Same issue. M2 chip, OS 13.1

**Comment by odlp** [comment]
Thanks for raising the issue, I'll take a look. I can't seem to replicate on MacOS 13.2 with a M1 chip at this time.

Please could someone confirm that the Bluetooth isn't being re-enabled after *unlocking* their Mac, with either password / touch ID?

**Comment by cheshi-mantu** [comment]
@odlp hi Oli,
M1, MB pro 16: 
initial state: Wifi ON BT ON
settings: 
**wifi turn off, BT turn off**
**wifi restore initial state, BT restore initial state**
**actual result**: WIFI is **OFF** after wake up, BT is **OFF** after wake up

initial state: Wifi ON BT ON
settings: 
**wifi turn off, BT turn off**
**wifi always enable, BT always enable**
**actual result**: WIFI is **ON** after wake up, BT is **OFF** after wake up

initial state: Wifi ON BT ON
settings: 
**wifi do nothing, BT turn off**
**wifi do nothing, BT restore the previous state**
**actual result**: WIFI is **ON** after wake up, BT is **OFF** after wake up

it looks like the restoration of the initial state on both – BT and WIFI does not work as expected if both are enabled and target state is to restore the initial state. Well, at least in my case.

**Comment by odlp** [comment]
@cheshi-mantu weird - this tool doesn't do anything to wifi. 

Are you you're using an official release from Homebrew or downloaded from this repo? (There are forks of Bluesnooze which add support for turning wifi off/on - like this one https://github.com/stefansundin/bluesnooze - but that's nothing to do with me)

**Comment by cheshi-mantu** [comment]
ah, my bad, you're right – wrong repo. 
but it seems there is the same issue with the reactivation of the connection.

**Comment by cheshi-mantu** [comment]
ah, my bad, you're right – wrong repo. 
but it seems there is the same issue with the reactivation of the connection.

**Comment by YubinXie** [comment]
My issue with bluetooth is that my mouse keeps waking my Mac mini without I touching it. I just found out that it is all because of Logitech option software. I updated to option+ and deleted option. Now I no longer need these tools to keep bluetooth off. JFI.

**Comment by gingerbeardman** [comment]
For me, I use this tool because my Bluetooth headphones wake my sleeping Mac when I only mean to use them on my iPhone.

**Comment by odlp** [comment]
Hi folks, I got a newer work laptop and was able to replicate this issue. I've rebuilt the app with a newer version on XCode and this appears to have fixed the problem.

Please give the new release a try - available on Homebrew or for [download here](https://github.com/odlp/bluesnooze/releases/tag/v1.2)

**Comment by gingerbeardman** [comment]
I just woke my computer up and bluetooth was still switched off.

macOS 12.6.8
Bluesnooze 1.2

**Comment by mminklet** [comment]
I am getting this issue, and I have been using the official app. I have upgraded Xcode. Started to happen after upgrading to Ventura 13.4.1 from 12.
