### ISSUE TITLE
Feature activate / deactivate ?

### ISSUE THREAD

**Issue by rpc31** [odlp/bluesnooze#20]
Hello, I love this app so much, but since I use bluetooth keyboard and trackpad, it, obviously, prevents my MacBook to get off out sleep with it. Is there a way to exclude some bluetooth devices from Bluesnoow or have a menu-bar option to deactivate / reactivate blue snooze ?

**Comment by gyro-labs** [comment]
+1

Disconnecting from specific devices would be favored over fully disabling bluetooth for me.

**Comment by odlp** [comment]
Sorry not looking to add per-device toggling - it'd be a complete re-write. Feel free to fork & experiment as you like ✌️

https://github.com/odlp/bluesnooze#can-you-add-support-for-selectively-disconnecting-certain-devices
