### ISSUE TITLE
Doesn't work with Hot Corners

### ISSUE THREAD

**Issue by elliotwaite** [odlp/bluesnooze#28]
Bluesnooze doesn't seem to work with Hot Corners.

To reproduce:
* Go to: System Settings > Desktop & Dock > Hot Corners...
* Then change the bottom right corner option to "Put Display to Sleep".
* Then click the "Done" button.
* Then move the mouse cursor to the bottom right corner of the screen, which will put the display to sleep, but it won't disable Bluetooth.

When I put the display to sleep using Apple Menu > Sleep, it works as expected, disabling Bluetooth, but nothing seems to happen when I put the display to sleep using Hot Corners.

Computer: MacBook Pro 15-inch, 2018
OS: macOS Ventura 13.2.1 (22D68)

**Comment by BtM909** [comment]
There is a difference between putting your display to sleep vs putting your Mac to sleep.

I always assumed this app only disables BT when you put your Mac to sleep.

**Comment by elliotwaite** [comment]
Ah, got it. Good point.
