### ISSUE TITLE
Adding this to homebrew

### ISSUE THREAD

**Issue by actuallymentor** [odlp/bluesnooze#3]
Have you considered adding this to homebrew?

**Comment by odlp** [comment]
Hi @actuallymentor,

I think Homebrew only accept Casks once an application has become a bit more widely known, reading their [rejected casks guidelines](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is for an app that is too obscure. Examples:
> - A self-submitted app from a GitHub repository that is not notable enough (under 30 forks, 30 watchers, and 75 stars).

But I've created a [custom tap](https://github.com/odlp/homebrew-bluesnooze) for the moment. Please could you try the following to install the app?

```sh
brew cask install odlp/bluesnooze/bluesnooze
```

(You may need to delete any previous versions not installed via Homebrew yourself)

Cheers,
Oli

**Comment by actuallymentor** [comment]
You want me to get you 75 stars? Takes a reddit post or two.

[Did it for my own app too](https://github.com/actuallymentor/wintertime-mac-background-freezer ).

**Comment by odlp** [comment]
@actuallymentor Ah I should give that a try sometime! 

Hopefully the user-tap should be sufficient for the moment. Please do let me know if you have any issues trying to install from it.

**Comment by actuallymentor** [comment]
I really prefer official casks. Do you object to me getting the stars and submitting to brew?

**Comment by odlp** [comment]
If you’re up for a star-hunt that’d be great 💫 

I’m happy to make a PR to the official cask repo once it hits 70 stars.

**Comment by actuallymentor** [comment]
I will commence `operation-starcatcher` today.

**Comment by odlp** [comment]
Bluesnooze is now available as an official cask (Homebrew/homebrew-cask#100234) so I'm going to close this issue.

Existing Homebrew users may want to untap: `brew untap odlp/homebrew-bluesnooze`
