### ISSUE TITLE
SHA256 mismatch on brew

### ISSUE THREAD

**Issue by RelicCornhusk** [odlp/bluesnooze#30]
Here is the output of my bluesnooze installation:

```➜  ~ brew install bluesnooze 
==> Downloading https://github.com/odlp/bluesnooze/releases/download/v1.2/Bluesn
==> Downloading from https://objects.githubusercontent.com/github-production-rel
         #-=O=#    #    #                                                      
Error: SHA256 mismatch
Expected: 075a8b7cf8f66d4f4002c62a1985a5d3fb043e3df09e7fd405e88ce24a96feb0
  Actual: 2e215dfb563974ded48b5972a08689eb6ecc70eb30af6e74aebb5a48be0b57f5
    File: /Users/myusername/Library/Caches/Homebrew/downloads/cc31ac694ced017817b22d29742228fb7e56236ae6646cf83c4a42b66bdd9937--Bluesnooze.zip
``` 
Already tried removing the file and retrying as well as performing a brew cleanup, followed by a brew upgrade and retrying the installation. 

Is this a problem that occurs for anyone else? Other brew formulas install just fine for me.

**Comment by odlp** [comment]
Hello,

Downloading the [v1.2 release](https://github.com/odlp/bluesnooze/releases/tag/v1.2) directly and checking the SHA256 still gives me the correct value, which matches the expected value above:

```
shasum -a 256 ~/Downloads/Bluesnooze.zip
075a8b7cf8f66d4f4002c62a1985a5d3fb043e3df09e7fd405e88ce24a96feb0
```

Might be worth trying a different internet connection? Could you try tethering via your phone? I wonder if something is tampering with the download on the way to you.

Might also be worth verifying the `brew cleanup` is doing what you hope it is - are there any entries listed when running `ls ~/Library/Caches/Homebrew/downloads`? (Could be a permissions issue and cleanup isn't actually clearing the cache)

**Comment by RelicCornhusk** [comment]
Sorry for the late reply,

I'm trying this on a corporate laptop, this could be why. Tethering the connection did not solve the problem unfortunately. And I double checked that brew cleanup was actually removing the file.

This issue can be closed as it's most likely some security application on my laptop creating problems. I was able to download the latest release manually.
