### ISSUE TITLE
Hide from the status bar

### ISSUE THREAD

**Issue by opryshok** [odlp/bluesnooze#4]
Is it possible to include the "Hide from the status bar" option as well?

**Comment by odlp** [comment]
Hi @opryshok,

To avoid writing code (less code is better 😄) could I ask if you've tried any third party menu bar managers? A quick google revealed the following options (I've not tried them):

- https://matthewpalmer.net/vanilla/
- https://www.macbartender.com/

Cheers,
Oli

**Comment by opryshok** [comment]
Thanks, @odlp. I appreciate what you did with the app. It works awesome.

I use Bartender but it hides apps. In this case, I didn't get why we need the icon in the status bar (there are many of them already). You set up Bluesnooze and forget about the problem. That's my point but I understand yours.

**Comment by FrankMono** [comment]
I do not understand why we should use third party menu bar managers, can you just hide them?

**Comment by odlp** [comment]
I've added the option to "Hide icon" in version 1.1. You can either `brew upgrade bluesnooze` or [download v1.1](https://github.com/odlp/bluesnooze/releases/tag/v1.1).

If for some reason you need to get the icon / UI back then you can run the follwing in your terminal: 

```
defaults delete com.oliverpeate.Bluesnooze hideIcon
```
