### ISSUE TITLE
Only disconnect certain devices

### ISSUE THREAD

**Issue by farzadyousefzadeh-synth** [odlp/bluesnooze#44]
Love the app ❤️ 

It'd be great if you could configure what devices stay connected or get disconnected. In my case, I'd like my headphone to get disconnected because it doesn't support multipoint connection and needs to be disconnected before I can connect it to another device. Would be awesome If I could tell the app to only disconnect that device and not my external keyboard for example.

**Comment by kopach** [comment]
Exactly the same reason I installed bluesnooze in the first place. Even though my headphone supports multi-device connection, Mac often is prioritized for some reason and I can't use headset on another device anyway

**Comment by n14s** [comment]
Same here

**Comment by odlp** [comment]
> ### Can you add support for selectively disconnecting certain devices?
> Bluesnooze is a really simple app which toggles the Bluetooth power on/off. Disconnecting specific devices would require a complete rewrite, and I don't need this functionality or the complexity it brings. Please feel free to fork & experiment as you like ✌️

https://github.com/odlp/bluesnooze?tab=readme-ov-file#can-you-add-support-for-selectively-disconnecting-certain-devices
