### ISSUE TITLE
Have an alternative "buy me a coffee" service

### ISSUE THREAD

**Issue by zkendall** [odlp/bluesnooze#5]
I tried yours and it said my VISA card is "Not Supported"...

Perhaps buymeacoffee.com which works with PayPal, or something else that does.

**Comment by odlp** [comment]
Thank you for trying to buy me a coffee. Sorry the Monzo option didn't work (I didn't realise it only works with cards from certain countries).

I've switched the link to buymeacoffee.com now.

Thanks again :raised_hands:
