### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by NgKhanh** [odlp/bluesnooze#6]
This app alway show dialog when startup, How to uninstall it?

**Comment by odlp** [comment]
Hi @NgKhanh,

You should just be able to delete `Bluesnooze.app` from your Applications folder, or wherever you placed the application. 

If that doesn't work you can try deselecting "Launch at login" from the menu bar as well:

<img width="181" alt="launch-at-login" src="https://user-images.githubusercontent.com/4125410/94126602-b9206180-fe4f-11ea-8c65-f42c2be704e3.png">

Thanks,
Oli

**Comment by NgKhanh** [comment]
I run app to disconnect bluetooth speaker while macbook sleeping, but it also disconect mouse and keyboard bluetooth

**Comment by odlp** [comment]
@NgKhanh yes, it completely turns off Bluetooth, rather than disconnecting from specific devices - this is by design.
