### ISSUE TITLE
No reconnection with my paired devices

### ISSUE THREAD

**Issue by varunpilankar** [odlp/bluesnooze#7]
I tried your app on macOS 10.15.4 but as soon as I installed it, I was not able to connect back to my paired devices.

Any fix for this?

**Comment by odlp** [comment]
Hi @varunpilankar. I'm still in MacOS Catalina too (10.15.7) and my bluetooth devices reconnect as expected.

If you manually turn off Bluetooth yourself, and turn it back on 5 minutes later, do your devices reconnect themselves? It might be possible the devices are entering a power-saving mode, and won't search for your Mac until they're been woken / turned off+on again. What kind of devices are they?

**Comment by varunpilankar** [comment]
**While BlueSnooze Install -** 

if you manually turn off Bluetooth yourself, and turn it back on 5 minutes later, do your devices reconnect themselves?
**NO**
It might be possible the devices are entering a power-saving mode, and won't search for your Mac until they're been woken / turned off+on again. 
**I don't think so, coz without BlueSnooze they work perfectly fine**

What kind of devices are they?
**Android Phone & Bluetooth Headset**

**Comment by odlp** [comment]
> if you manually turn off Bluetooth yourself, and turn it back on 5 minutes later, do your devices reconnect themselves?
NO

If your devices aren't reconnecting automatically when you toggle bluetooth on/off by hand, then it won't be any different when Bluesnooze turns bluetooth on/off. That's up to the operating system + devices (Bluesnooze doesn't have any auto-reconnect functionality because that's beyond it's remit in my opinion).

Hope you can find a solution suitable to your needs. There are some other options with `blueutil` and other tools where you can make your own script: https://apple.stackexchange.com/questions/365055/disable-bluetooth-or-disconnect-bluetooth-connections-when-lid-is-closed

**Comment by varunpilankar** [comment]
Currently without any app/scripts its does connect automatically. 

The only reason I was interested in your solution - when my mac is sleeping but the Bluetooth is On, my phone & headset connects to the mac automatically which is very irritating.

I also tried **Alberto Lerdo** script, that is also giving me the same issue.

**Comment by iannotian** [comment]
This really depends on your device. I have the same exact behavior, but it's not your computer's or the script's fault.

My QC35 headphones will not initiate a connection unless they are freshly turned on or in connect mode (2 sec hold of power switch) is engaged. IME with this script, Bluetooth sometimes takes a while (>15s) to turn on after lid open. That is the biggest flaw with the script, and I'm not sure if it's even the script's fault. Turns off immediately after lid close, though.

So... for this to work, I have to open my laptop, wait for Bluetooth to turn on, then turn my headphones on. If I turn my headphones on while Bluetooth is off or when the lid is closed, I have to initiate connect mode on my headphones. Not a big deal. Much better than it connecting while my Mac is asleep, I think.

Really wish Apple would make a clean solution for this, like adding a checkbox in Bluetooth preferences that reads: "Allow this device to wake this Mac" or "Allow this device to connect during sleep". Maybe their answer is to tell you to buy a pair of AirPods Studio headphones. I don't know.

**Comment by varunpilankar** [comment]
I got it fixed for my TWS using the script purely running through brew and not the app

**Comment by odlp** [comment]
Glad you found a solution @varunpilankar, I'm going to close this issue just to tidyup.
