### ISSUE TITLE
 Compatibility with Big Sur

### ISSUE THREAD

**Issue by phamleduy04** [odlp/bluesnooze#8]
I have used this app when I was on Catalina, but I don't know does it works in Big Sur? Thanks a lot!

**Comment by rffensick** [comment]
@phamleduy04 Work's fine.

**Comment by odlp** [comment]
Thanks for verifying @rffensick. I'll get round to upgrading my laptop to Big Sur when I'm feeling brave 😅 

@phamleduy04 I'm going to close this issue for now, but please feel free to re-open if you discover any issues.
